(function(){
    'use strict';

    /**
     * This is a sample directive
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('common').directive('confirmPassword', function() {

        return {
            require: "ngModel",
            restrict: "A",
            scope: {
                otherModelValue: "=confirmPassword"
            },

            link: function (scope, element, attributes, ngModel) {

                ngModel.$validators.psCompareTo = function (modelValue) {
                    return modelValue === scope.otherModelValue;
                };

                // scope.$watch("otherModelValue", function () {
                //     ngModel.$validate();
                // });
            }
        };

    });

})();
